version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_PASSWORD=zaq12wsx
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=zaq12wsx
    volumes:
      - ./mariadb-data:/bitnami
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=zaq12wsx
      - MOODLE_EMAIL=admin@empty.com
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=zaq12wsx
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./mdl-data:/bitnami
    depends_on:
      - mariadb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mariadb-data:
    driver: local
